name: Download Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      
      - name: Download release
        uses: robinraju/release-downloader@v1.6
        with:
          latest: true
          fileName: "spacegameleaderboard.zip"
      
      - name: list files
        run: |
          ls
          
      - name: list files
        run: |
          curl \
           -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer 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" \
                    https://api.github.com/repos/CanarysPlayground/repo-template1/releases \
                 -d '{"tag_name":"1.0","target_commitish":"main","name":"spacegameleaderboard.zip","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
